#!/usr/bin/env bash
source "$DOROTHY/sources/bash.bash"

git init

files=(".editorconfig" ".gitignore" ".npmignore")
for file in "${files[@]}"; do
	github-download \
		--slug="bevry/base" \
		--pathname="$file"
done

if is-missing package.json; then
	npm init -y
fi
