#!/usr/bin/env bash

function campjs_command() (
	source "$DOROTHY/sources/bash.bash"

	local who
	who="$(ask --question='Who are you?' | echo-lowercase --stdin)"

	local colors=()
	mapfile -t colors < <(
		choose --default=red --default=blue --multi --question='What is your favourite color?' \
			-- green red blue blink jkasdjkasdjkas
	)

	local color
	for color in "${colors[@]}"; do
		if test "$color" = 'blink'; then
			if ! confirm --linger --positive --ppid=$$ -- 'Are you sure?'; then
				echo-style --notice='Good choice not to blink.'
				return 0
			fi
		fi
		echo-style --"$color"="Hello $who"
	done

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	campjs_command "$@"
fi
