#!/usr/bin/env bash

function can_backup() (
	# @todo figure out a better option for this
	# Arq (like cron) does not inherit the shell environment.
	# [say] does not work in this environment: Open speech channel failed: -915
	if test -z "$DOROTHY"; then
		DOROTHY="$HOME/.local/share/.dorothy"
	fi
	source "$DOROTHY/sources/bash.bash"

	# test streaming
	if "$DOROTHY/commands/is-streaming"; then
		__print_lines 'Streaming is occurring, cancelling backup.' >/dev/stderr
		return 1
	else
		__print_lines 'No streaming is occuring, commencing backup.'
		return 0
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	can_backup "$@"
fi
