#!/usr/bin/env bash

# `say` does not work in this environment:
# Open speech channel failed: -915

# todo, consider cleaning this somewhow
# arq does not inherent shell environment
if test -z "$DOROTHY"; then
	DOROTHY='/Users/balupton/.dorothy'
fi

# ensure failures are propagated
source "$DOROTHY/sources/strict.bash"

# test streaming
if "$DOROTHY/commands/is-streaming"; then
	echo 'Streaming is occurring, cancelling backup.' >/dev/stderr
	exit 1
else
	echo 'No streaming is occuring, commencing backup.'
	exit 0
fi
