#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function echo-count () (

	# =====================================
	# Arguments

function help {
	cat <<-EOF >/dev/stderr
		ABOUT:
		For each input, count its characters or words.

		USAGE:
		echo-count [...options] <...input>
		echo-lines <...input> | echo-count [...options]

		OPTIONS:
		-w, --words
			Count words instead of characters.

		EXAMPLE:

		echo-count 'hello'

		    5
		    # exit status: 0

		echo-lines 'hello' | echo-count

		    5
		    # exit status: 0

	EOF
	return 22 # Invalid argument
}

	# process
	local item words='no' ARGS=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'-w'|'--words') words='yes' ;;
		'--')
			ARGS+=("$@")
			shift "$#"
			break
			;;
		*) ARGS+=("$item") ;;
		esac
	done

	# =====================================
	# Act

	if test "$words" = 'yes'; then
		function counter { wc -w; }
	else
		function counter { wc -m; }
	fi

	function on_input {
		printf '%s' "$1" | counter | echo-trim-each-line
	}

	source "$DOROTHY/sources/stdinargs.bash"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	echo-count "$@"
fi
