#!/usr/bin/env bash
source "$DOROTHY/sources/bash.bash"

function help {
	cat <<-EOF >/dev/stderr
		ABOUT:
		For each input, count its characters.

		USAGE:
		echo-count <...input>
		echo-lines <...input> | echo-count

		EXAMPLE:

		echo-count 'hello'

		    5
		    # exit status: 0

		echo-lines 'hello' | echo-count

		    5
		    # exit status: 0

	EOF
	return 22 # Invalid argument
}

function on_input {
	printf '%s' "$1" | wc -m | echo-trim-each-line
}

source "$DOROTHY/sources/stdinargs.bash"
