#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
# https://discuss.bevry.me/t/creating-managing-a-discourse-instance/691?u=balupton

sshpass="$(secret get BEVRY_DISCOURSE_SSH)"
sshfile='/root/.ssh/root-discuss.bevry.me-github'
sshhelp='/root/ssh_stdin_password.bash'

ssh -T discourse <<EOF
$(cat "$DOROTHY/sources/strict.bash")

# Check discourse is already setup
if ! test -d /var/discourse; then
	echo 'Run this command on the remote discourse server'
	exit 1
fi

# Work around SSH password: https://stackoverflow.com/a/52671286/130638
rm -f "$sshhelp"
echo '#!/usr/bin/env bash' >> "$sshhelp"
echo 'read secret' >> "$sshhelp"
echo 'echo \$secret' >> "$sshhelp"
chmod +x "$sshhelp"

echo 'Adding the SSH keys...'
eval "\$(ssh-agent -s)"
DISPLAY=:0 SSH_ASKPASS="$sshhelp" ssh-add "$sshfile" <<< "$sshpass"

echo 'Updating the local server configuration...'
cd /
git fetch origin
git pull origin "\$(git rev-parse --abbrev-ref HEAD)"

echo 'Updating the discourse docker setup...'
cd /var/discourse
git pull origin master

echo 'Rebuilding the discourse docker instance...'
/var/discourse/launcher rebuild app
EOF
