#!/usr/bin/env bash

function echo_progress() (
	source "$DOROTHY/sources/stdinargs.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Continue reading a number from STDIN, that will be between 0 and 100 and will be newline separated, and update the progress bar in the terminal title bar to the progress percentage that the number represents.

			USAGE:
			{ for (( i=0; i<=100; i+=20 )); do sleep 20; echo \$i; done; } | echo-progress

			OPTIONS:
			$(__stdinargs__help_options --)
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# =====================================
	# Action

	__terminal_title_progress_bar --create
	__terminal_title_progress_bar --progress=0
	function __on_line {
		__terminal_title_progress_bar --progress="$1" || return
	}
	function __on_finish {
		__terminal_title_progress_bar --destroy || return
	}

	stdinargs --no-timeout "${option_args[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	echo_progress "$@"
fi
