#!/usr/bin/env bash

function ffmpeg_separate() (
	source "$DOROTHY/sources/bash.bash"

	local arg filename
	for arg in "$@"; do
		filename="${arg%.mov*}"

		ffmpeg -i "$arg" -map 0:0 -map 0:2 -c copy "$filename [00+02].mov"
		ffmpeg -i "$arg" -map 0:1 -map 0:3 -c copy "$filename [01+03].mov"
	done
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	ffmpeg_separate "$@"
fi
