#!/usr/bin/env bash
source "$DOROTHY/sources/essentials.sh"
source "$DOROTHY/sources/strict.bash"

if test -z "${1-}"; then
	stderr echo 'USAGE: fix-permissions <...dir>'
	exit 1
fi
if test -z "${user-}"; then
	stderr echo 'USAGE: env user=<user> fix-permissions <...dir>'
	exit 1
fi
if test -z "${group-}"; then
	stderr echo 'USAGE: env group=<group> fix-permissions <...dir>'
	exit 1
fi

function act {
	sudo -H -u "$user" "$@" || sudo "$@" || echo "failed to run: $*"
	echo
}

for dir in "$@"; do
	echo
	ls -la "$dir"
	echo
	act chown -Rv "$user:$group" "$dir"
	act chmod -Rv g+rwx "$dir"
	act chmod -Rv u+rwx "$dir"
	echo
	ls -la "$dir"
	echo
done
