#!/usr/bin/env bash

function github_auth() (
	source "$DOROTHY/sources/bash.bash"

	# trim
	if test "${1-}" = '--'; then
		shift
	fi

	# if the secrets aren't provided, fetch them and reload
	if test -z "${GITHUB_ACCESS_TOKEN-}"; then
		echo-style 'Environment variable ' --code='GITHUB_ACCESS_TOKEN' ' is empty, fetching it from the secret engine...' >/dev/tty
		secret env GITHUB_ACCESS_TOKEN -- "$@"
		return
	else
		"$@"
		return
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	github_auth "$@"
fi
