#!/usr/bin/env bash

function gtd() (
	source "$DOROTHY/sources/bash.bash"

	local branch_or_tag="$1"
	git branch -D "$branch_or_tag" || :
	git tag -d "$branch_or_tag" || :
	local remotes=() remote
	mapfile -t remotes < <(git-helper remotes)
	for remote in "${remotes[@]}"; do
		git push "$remote" :"$branch_or_tag" || :
	done
	git fetch --all --prune
	git branch -a
)

# fire if invoked standalone
if [[ "$0" = "${BASH_SOURCE[0]}" ]]; then
	gtd "$@"
fi
