#!/usr/bin/env bash

function gtd() (
	source "$DOROTHY/sources/bash.bash"

	local tag="$1"
	git tag -d "$tag"
	git push origin :"$tag"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	gtd "$@"
fi
