#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# stop the apps first, obviously
if test -f "$DOROTHY/user/env/seedbox.bash"; then
	seedbox-runner stop
fi

# then unmount everything and shutdown
unmount-all

# ask the user if reboot or shutdown
echo 'Do you want to reboot or shutdown?'
action="${1:-"$(choose reboot shutdown)"}"
if test "$action" = "reboot"; then
	sudo shutdown --reboot
else
	sudo shutdown --poweroff
fi
