#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# make sure vaults are possible
setup-gocryptfs

# mount our volumes and vaults
mount-all

# start our apps
if test -f "$DOROTHY/user/env/seedbox.bash"; then
	seedbox start
fi
