#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# mount our volumes and vaults
mount-all

# restart share
sudo systemctl restart smbd || :
sudo systemctl restart plexmediaserver || :
sudo systemctl restart resilio-sync || :

# start our apps
if test -f "$DOROTHY/user/env/seedbox.bash"; then
	seedbox start
fi
