#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# stop the apps first, obviously
if test -f "$DOROTHY/user/env/seedbox.bash"; then
	seedbox stop
fi

# then unmount everything and shutdown
unmount-all

# ask the user if reboot or shutdown
echo 'Machine ready for closure. What would you like to do?'
action="${1:-"$(choose reboot poweroff nothing)"}"
if test "$action" = 'reboot' -o "$action" = 'restart'; then
	sudo shutdown --reboot
elif test "$action" = 'poweroff' -o "$action" = 'shutdown'; then
	sudo shutdown --poweroff
else
	echo 'Leaving for you to reboot or poweroff.'
fi
