#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function magnet-select () (
	# prepare
	search="$1"

	# fetch
	echo-purple "searching" >/dev/tty
	mapfile -t results < <(magnet-search "$search")
	if test "${#results[@]}" -eq 0; then
		return 1
	fi

	# select
	choose-option \
		--question="Which magnet for $search?" \
		--label=first \
		--visual='$(echo-magnet-hash "$value")    $label' \
		-- "${results[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	magnet-select "$@"
fi
