#!/usr/bin/env bash

function magnet_select() (
	source "$DOROTHY/sources/bash.bash"
	require_array 'mapfile'

	# prepare
	local search="$1" results option_visual

	# fetch
	echo-style --purple='searching' >/dev/tty
	mapfile -t results < <(magnet-search "$search")
	if test "${#results[@]}" -eq 0; then
		return 1
	fi

	# select
	# trunk-ignore(shellcheck/SC2016)
	option_visual='$(echo-magnet-hash "$value")    $label'
	choose-option \
		--question="Which magnet for $search?" \
		--label=first \
		--visual="$option_visual" \
		-- "${results[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	magnet_select "$@"
fi
