#!/usr/bin/env bash
source "$DOROTHY/sources/bash.bash"
require_array 'mapfile'

# dependencies
source "$DOROTHY/sources/ripgrep.bash"

# prepare
search="$1"

# https://github.com/casey/intermodal

# https://github.com/juliensalinas/torrengo

# https://github.com/rndusr/torf-cli

# https://github.com/rndusr/stig
# pipx run stig add "$search"
# stig -h cmds

# https://github.com/florinutz/yts
# env CARGO='yts' setup-util cargo
# yts list "$filename"

# https://github.com/bleusakura/magnetfinder
# env CARGO='magnetfinder' setup-util cargo
# magnetfinder -yq "$filename" --sort size
# ^ doesn't work well programatically

# https://crates.io/crates/tpb
# tpb -q
# ^ doesn't work

# https://github.com/rnestler/attractorr aka torrent-search
# https://github.com/rnestler/attractorr/issues/55
# CARGO='--git https://github.com/rnestler/attractorr --tag v0.2.0'
setup-util --quiet --cli='attractorr' \
	CARGO='--git https://github.com/rnestler/attractorr'
mapfile -t lines < <(attractorr --sort=seeders "$search" 2>&1 || :)
for line in "${lines[@]}"; do
	line="$(echo-no-colors "$line")"
	if test -z "$line" || rg -q 'ERROR|No results|btih:000000000000' <<<"$line"; then
		continue
	fi
	echo "$line"
done

# magnetfinder
# https://github.com/bleusakura/magnetfinder
setup-util --quiet --cli='magnetfinder' \
	CARGO='magnetfinder'
mapfile -t lines < <(magnetfinder --no-interactive --show 5 -aq "$search" 2>/dev/null | rg -v 'No torrents found matching search query' || :)
echo-split $'\t' -- "${lines[@]}"
