#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

function mount_drive {
	local mount_source="$1"
	local mount_target="$2"
	sudo mkdir -p "$mount_target"
	echo "$mount_source => $mount_target"
	sudo umount -l "$mount_target" || echo 'already unmounted'
	sudo mount "$mount_source" "$mount_target"
	sudo btrfs dev stats "$mount_target"
	fix-permissions "$mount_target"
}

function mount_drives {
	local previous_item=''
	for item in "$@"; do
		if test -z "$previous_item"; then
			previous_item="$item"
		else
			mount_drive "$previous_item" "$item"
			previous_item=''
		fi
	done
}

if test "$#" -ne 0; then
	mount_drives "$@"
elif test -f "$DOROTHY/user/env/mount-locations.bash"; then
	source "$DOROTHY/user/env/mount-locations.bash"
	mount_drives "${MOUNT_DRIVES[@]}"
else
	stderr echo 'USAGE: mount-drives "/source" "/target" ..."'
fi
