#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# args
filter="${1-}"

# config
varfile="$DOROTHY/user/env/downloads.bash"
if test -f "$varfile"; then
	source "$varfile"
else
	stderr echo "config file missing: $varfile"
	exit 1
fi
# check config
if test -z "${completed-}"; then
	stderr echo 'completed configuration missing'
	exit 1
fi
if test -z "${categories-}"; then
	stderr echo 'categories configuration missing'
	exit 1
fi

# which
echo 'Which download do you want to move?'
what="$(choose-path "$completed" "$filter")"
dir="$(basename "$what")"
echo

# if test -z "$what"; then
# 	stderr echo 'All downloads already moved...'
# 	exit 1
# fi

# title
title="$(echo "$dir" | sd '[.]' ' ' | sd '(.+?)\s*[(]?([12][90][0-9][0-9])[)]?.*' '$1 [$2]')"
title="$(ask --question='What do you want to call it?' --default="$title")"
echo

# destination
category=''
destination="$(choose-option --question='What is it?' --filter="$category" --label=first -- "${categories[@]}")"
if test -n "$title"; then
	destination="$(fs-join "$destination" "$title")"
fi
echo

echo "We will MOVE"
echo "=> $what"
echo "into the directory:"
echo "=> $destination"
confirm-positive "is that okay?"
echo

result="$(fs-join "$destination" "$dir")"
if test -f "$result"; then
	echo 'Already exists at:'
	echo "=> $result"
	if confirm-postive 'overwite?'; then
		rm -Rfv "$result"
	else
		exit 1
	fi
fi

mkdir -p "$destination"
mv "$what" "$destination"
fix-permissions "$result"

echo
echo 'Moved successfully, here are the results:'
echo-paths "$destination"