#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# config
varfile="$DOROTHY/user/env/downloads.bash"
if test -f "$varfile"; then
	source "$varfile"
else
	stderr echo "config file missing: $varfile"
	exit 1
fi
# check config
if test -z "${completed-}"; then
	stderr echo 'completed configuration missing'
	exit 1
fi
if test -z "${categories-}"; then
	stderr echo 'categories configuration missing'
	exit 1
fi
catnames="$(array-odds "${categories[@]}")"
catpaths="$(array-evens "${categories[@]}")"

# which
echo 'Which download do you want to move?'
what="$(choose-path "$completed")"
dir="$(basename "$what")"
echo

# if test -z "$what"; then
# 	stderr echo 'All downloads already moved...'
# 	exit 1
# fi

echo 'What do you want to call it?'
read -r title
echo

echo 'What is it?'
category="$(choose "${catnames[@]}")"
echo

destination=''
for i in $(seq 0 1 ${catnames[#]}); do
	v="${catnames[$i]}"
	if test "$v" = "$category"; then
		destination="${catpaths[$i]}"
done
if test -z "$destination"; then
	stderr echo 'invalid category configuration'
	exit 1
fi

if test -n "$title"; then
	destination="$(fs-join "$destination" "$title")"
fi

echo "We will MOVE"
echo "=> $what"
echo "into the directory:"
echo "=> $destination"
confirm-positive "is that okay?"
echo

result="$(fs-join "$destination" "$dir")"
if test -f "$result"; then
	echo 'Already exists at:'
	echo "=> $result"
	if confirm-postive 'overwite?'; then
		rm -Rfv "$result"
	else
		exit 1
	fi
fi

mkdir -p "$destination"
mv "$what" "$destination"
fix-permissions "$result"

echo
echo 'Moved successfully, here are the results:'
echo-paths "$destination"