#!/usr/bin/env bash

function new_dev_branch() (
	source "$DOROTHY/sources/bash.bash"

	# dependencies
	if ! is-file -- /usr/share/dict/words; then
		if is-apt; then
			# https://askubuntu.com/a/149128
			# setup-util --name='American Words' APT='wamerican'
			setup-util --name='British Words' APT='wbritish'
		else
			__print_error 'No dictionary found'
			return 1
		fi
	fi

	# use two words, so you don't just end up with one inappropriate word like:
	# > new-dev-branch
	# Switched to a new branch 'dev/marijuana'
	#
	# okay, don't use two words either:
	# > new-dev-branch
	# Switched to a new branch 'dev/sleaziness-greening'
	#
	# instead prompt them

	# action
	local word branch question
	while :; do
		#words="$(shuf -n 1 /usr/share/dict/words | echo-join '-' --stdin | echo-lowercase --stdin | echo-lines --prefix='dev/' --stdin)"
		word="$(shuf -n 1 /usr/share/dict/words)"
		# check it is a valid word, unlike: Olympiad, haiphong's, chancel's
		if ! echo-regexp -qf --regexp='^[a-z]+$' -- "$word"; then
			continue # generate another
		fi
		branch="dev/$word"
		question="$(echo-style --reset --bold='use ' --invert="$branch" --bold=' as the new branch name?')"
		if confirm --positive --ppid=$$ -- "$question"; then
			break
		fi
	done
	git checkout -b "$branch"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	new_dev_branch "$@"
fi
