#!/usr/bin/env bash
source "$DOROTHY/sources/bash.bash"

old="$1"
new="$2"
url="https://www.npmjs.com/package/$new"
message="$old has been renamed to $new: npm uninstall ${old@Q} && npm install ${new@Q} && open ${url@Q}"
npm deprecate "$old" "$message"
