#!/usr/bin/env bash

function npm_redo() (
	source "$DOROTHY/sources/bash.bash"

	rm-modules
	npm i
	npm run our:release:prepare
	npm link
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	npm_redo "$@"
fi
