#!/usr/bin/env bash

function npm_redo() (
	source "$DOROTHY/sources/bash.bash"

	rm-modules
	nvm-env npm i
	nvm-env npm run our:release:prepare
	nvm-env npm link
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	npm_redo "$@"
fi
