#!/usr/bin/env bash

function padd() (
	source "$DOROTHY/sources/bash.bash"

	# help
	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Forward to the correct package manager for your project.
			If [yarn.lock] is present, uses [yarn].
			If [package.json] is present, uses [package.json].

			USAGE:
			padd ...
		EOF
		return 22 # EINVAL 22 Invalid argument
	}
	if is-help -- "$@"; then
		help
	fi

	# act
	if test -f 'yarn.lock'; then
		yarn add "$@"
	elif test -f 'package.json'; then
		npm install "$@"
	else
		help 'Could not determine the correct package manager this project.' || :
		return 43 # EPROTONOSUPPORT 43 Protocol not supported
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	padd "$@"
fi
