#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"
source "$DOROTHY/sources/config.sh"

# dependencies
setup-util-deno --quiet

# configuration:
tuples=()
load_dorothy_config 'permanence.bash'

# verify
if test "${#tuples[@]}" -eq 0; then
	echo "make sure $(get_dorothy_config 'permanence.bash') outputs an array called tuples, of the sources and destinations" >/dev/stderr
	exit 1
fi
if is-odd "${#tuples[@]}"; then
	echo "the tuples do not seem to have one destination for one source" >/dev/stderr
	exit 1
fi

# cycle
for ((i = 0; i < ${#tuples[@]}; i = i + 2)); do
	src="${tuples[$i]}"
	dest="${tuples[$i + 1]}"
	mkdir -p "$dest"
	cd "$dest" || exit 1
	ref="$(get-url-domain "$src")"
	ytd-helper --archive --referer "$ref" "$src"
done
