#!/usr/bin/env bash

function permanence() (
	source "$DOROTHY/sources/bash.bash"
	source "$DOROTHY/sources/config.sh"

	# dependencies
	setup-util-deno --quiet

	# configuration:
	local tuples=()
	load_dorothy_config 'permanence.bash'

	# verify
	if [[ "${#tuples[@]}" -eq 0 ]]; then
		__print_lines "make sure $(get_dorothy_config 'permanence.bash') outputs an array called tuples, of the sources and destinations" >/dev/stderr
		return 1
	fi
	if is-odd -- "${#tuples[@]}"; then
		__print_lines 'the tuples do not seem to have one destination for one source' >/dev/stderr
		return 1
	fi

	# cycle
	local i src dest ref
	for ((i = 0; i < ${#tuples[@]}; i = i + 2)); do
		src="${tuples[$i]}"
		dest="${tuples[i + 1]}"
		__mkdirp "$dest"
		cd "$dest"
		ref="$(get-url-domain "$src")"
		ytd-helper --archive --referer "$ref" "$src"
	done
)

# fire if invoked standalone
if [[ "$0" = "${BASH_SOURCE[0]}" ]]; then
	permanence "$@"
fi
