#!/usr/bin/env bash

function remove_part_extension() (
	source "$DOROTHY/sources/bash.bash"

	local files=() file
	__split --target={files} --no-zero-length --stdin < <(find-files --extension=part . || :)
	if [[ ${#files[@]} -eq 0 ]]; then
		__print_style --notice='No files to process.'
		return 0
	fi
	for file in "${files[@]}"; do
		mv -v -- "$file" "${file%.part}"
	done
	__print_style --success="Removed part extension from ${#files[@]} files."
	return 0
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	remove_part_extension "$@"
fi
