#!/usr/bin/env bash

function remove_duplicates() (
	source "$DOROTHY/sources/bash.bash"

	local src="$1" file filename alternative altfile file_hashf altfile_hashf
	shift

	# cycle through src files
	for file in "$src"/*; do
		filename="$(basename "$file")"
		for alternative in "$@"; do
			# check it also exists in alt location
			altfile="$alternative/$filename"
			if test ! -f "$altfile"; then
				continue
			fi

			# prepare
			file_hashf="$(mktemp)"
			altfile_hashf="$(mktemp)"

			# checksum
			echo
			echo-style --bold="$file"
			checksum --untitled --algorithm=md5 -- "$file" | tee "$file_hashf"
			echo-style --bold="$altfile"
			checksum --untitled --algorithm=md5 -- "$altfile" | tee "$altfile_hashf"

			# compare and possibly remove
			if test "$(cat "$file_hashf")" = "$(cat "$altfile_hashf")"; then
				rm "$altfile"
				echo-style --green='same,' --green+bold=' removed: ' --dim="$altfile"
			else
				echo-style --red='different,' --red+bold=' kept'
			fi
		done
	done
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	remove_duplicates "$@"
fi
