#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# 192.168.4.42
source_host="$(ask-mandatory "What is the hostname you want to restore from?" "${1-}")"
# balupton
source_user="$(ask-mandatory "What is the username on that host?" "${2-}")"

export TOOL=rsync
export ACTION=copy
function do_restore {
	cpr "$source_user"@"$source_host":"$1" "$2"
}
function do_home_restore {
	dir="$1"
	src="$(fs-join "/home/${source_user}" "$dir")"
	target="$(fs-join "$HOME" "$dir")"
	cpr "$source_user"@"$source_host":"$src" "$target"
}

echo 'Restoring essentials...'
do_home_restore .ssh/
do_home_restore .gnupg/
do_home_restore .dorothy/user/
