#!/usr/bin/env bash

function sbs_helper() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >&2
			ABOUT:
			Get details about your watched files.

			USAGE:
			sbs-helper [...options]

			OPTIONS:
			--token=<token>
			    Your bearer token.
		EOF
		if [[ $# -ne 0 ]]; then
			__print_error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item token=''
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--token='*) token="${item#*=}" ;;
		--*) __unrecognised_flag "$item" || return ;;
		*) __unrecognised_argument "$item" || return ;;
		esac
	done

	# ensure token
	if [[ -z $token ]]; then
		question="$(__print_style --bold="What is your bearer token?" $'\n' "Fetch this by logging into SBS, and monitoring your web console for " --code="/all?context=odwebsite" ' then grabbing it from the request headers.')"
		token="$(ask --question="$question")"
	fi

	# =====================================
	# Arguments

	function __get_watched {
		http --auth "$token" --auth-type 'bearer' 'https://www.sbs.com.au/api/v3/video_progress/all?context=odwebsite' | jq -r '.all | .response | to_entries | map ( {id: .key, completed: .value.completed} ) | .[] | select(.completed==1) | .id' || return
	}

	function __fetch_title {
		local id
		for id in "$@"; do
			http --auth "$token" --auth-type 'bearer' "https://www.sbs.com.au/api/v3/video_search/fetchbyIds?n=${id}&context=odwebsite&range=1-10" | jq -r '.itemListElement | .[] | .name + " (" + .datePublished[0:4] + ")"' || return
		done
	}

	local ids=()
	__split --target={ids} --no-zero-length --invoke -- \
		__get_watched
	__fetch_title "${ids[@]}"
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	sbs_helper "$@"
fi
