#!/usr/bin/env bash

function screentime_work() (
	source "$DOROTHY/sources/bash.bash"

	# =====================================
	# Arguments

	function __help {
		__print_help "$@" <<-EOF || return $?
			ABOUT:
			Fetches the amount of time I spent working via the Screen Time feature of macOS.

			USAGE:
			\`screentime-work [...options]\`

			OPTIONS:
			--quiet
			    If enabled, do not output any messages.

			--update
			    Update the data jar \`screentime-work\` with the latest seconds.
		EOF
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local item option_quiet='no' option_update='no' screentime_args=()
	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		--help | -h) __help || return $? ;;
		--no-quiet* | --quiet*) __flag --source={item} --target={option_quiet} --affirmative --coerce || return $? ;;
		--no-update* | --update*) __flag --source={item} --target={option_update} --affirmative --coerce || return $? ;;
		--)
			screentime_args+=("$@")
			shift $#
			break
			;;
		*) screentime_args+=("$item") ;;
		esac
	done

	local shared_args=()
	if [[ $option_quiet == 'yes' ]]; then
		shared_args+=('--quiet')
	elif [[ $option_quiet == 'no' ]]; then
		shared_args+=('--quiet=false')
	fi

	# =====================================
	# Action

	function __fetch {
		screentime "${shared_args[@]}" vscode gitfox terminal ghostty finder github vercel.com cloudflare.com bevry.me "${screentime_args[@]}" "$@" || return $?
	}

	if [[ $option_update == 'yes' ]]; then
		local result
		result="$(__fetch --seconds)" || return $?
		if [[ -n $result ]]; then
			set-data-jar "${shared_args[@]}" 'screentime-work' "$result" || return $?
		fi
	else
		__fetch || return $?
	fi
)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	screentime_work "$@"
fi
