#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

action="${1:-'start'}"
image='haugene/transmission-openvpn'

# config
varfile="$DOROTHY/user/env/seedbox.bash"
if test -f "$varfile"; then
	source "$varfile"
else
	stderr echo "config file missing: $varfile"
	exit 1
fi

# config check
if test -z "${seedboxport-}"; then
	seedboxport='9091'
fi
if test -z "${vpnprovider-}"; then
	vpnprovider='NORDVPN'
fi
if test -z "${datapath-}"; then
	stderr echo 'datapath configuration missing'
	exist 1
fi
if test -z "${vpnuser-}"; then
	stderr echo 'vpnuser configuration missing'
	exist 1
fi
if test -z "${vpnpass-}"; then
	stderr echo 'vpnpass configuration missing'
	exist 1
fi

# actions
function seedbox_ip {
	sudo docker exec -it "$id" curl -fsSL 'http://ipecho.net/plain'
}
function seedbox_id {
	# fetch container identifier
	# sudo docker container ls
	# sudo docker ps
	sudo docker ps --filter ancestor="$image" --format '{{ .ID }}'
}
function seedbox_create {
	sudo docker run --cap-add=NET_ADMIN -d \
		-v "$datapath":/data \
		-e OPENVPN_PROVIDER="$vpnprovider" \
		-e OPENVPN_USERNAME="$vpnuser" \
		-e OPENVPN_PASSWORD="$vpnpass" \
		-e OPENVPN_OPTS='--inactive 3600 --ping 10 --ping-exit 60' \
		-e NORDVPN_CATEGORY=legacy_p2p \
		-e LOCAL_NETWORK=192.168.0.0/16 \
		--restart=always \
		--log-driver json-file \
		--log-opt max-size=10m \
		-p "$seedboxport":"$seedboxport" \
		"$image"

	id="$(seedbox_id)"
	# ensure that it does not automatically start with the system
	sudo docker update --restart=no "$id"
}
function seedbox_stop {
	id="$(seedbox_id)"
	sudo docker stop --time 60 "$id"
	echo "seedbox stopped successfully"
}
function seedbox_status {
	id="$(seedbox_id)"
	localip="$(ip-local)"
	hostip="$(ip-remote)"
	seedboxip="$(seedbox_ip)"
	details=(
		"host ip      =  $hostip"
		"seedbox ip   =  $seedboxip"
		"seedbox url  =  http://$localip:$seedboxport"
	)
	if test "$hostip" != "$seedboxip"; then
		echo 'seedbox booted successfully'
		echo-args "${details[@]}"
	else
		echo 'seedbox did not connect to the vpn it seems'
		echo-args "${details[@]}"
		exit 1
	fi
}
function seedbox_start {
	id="$(seedbox_id)"
	sudo docker start "$id"
	seedbox_status
}

# if the action is stop, then stop it
if test "$action" = 'stop'; then
	seedbox_stop
elif test "$action" = 'start'; then
	seedbox_start
elif test "$action" = 'status'; then
	seedbox_status
elif test "$action" = 'id'; then
	seedbox_id
elif test "$action" = 'create'; then
	seedbox_create
else
	stderr echo 'USAGE: seeedbox-runner <start|stop|status|id|create>'
	exit 1
fi
