#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

conf="$DOROTHY/user/env/seedbox.bash"
if test -f "$config"; then
	source "$config"
else
	stderr echo "config file missing: $config"
	exit 1
fi

if test -z "${seedboxport-}"; then
	seedboxport='9091'
fi
if test -z "${vpnprovider-}"; then
	vpnprovider='NORDVPN'
fi
if test -z "${datapath-}"; then
	stderr echo 'datapath configuration missing'
	exist 1
fi
if test -z "${vpnuser-}"; then
	stderr echo 'vpnuser configuration missing'
	exist 1
fi
if test -z "${vpnpass-}"; then
	stderr echo 'vpnpass configuration missing'
	exist 1
fi

sudo docker run --cap-add=NET_ADMIN -d \
	-v "$datapath":/data \
	-e OPENVPN_PROVIDER="$vpnprovider" \
	-e OPENVPN_USERNAME="$vpnuser" \
	-e OPENVPN_PASSWORD="$vpnpass" \
	-e OPENVPN_OPTS='--inactive 3600 --ping 10 --ping-exit 60' \
	-e NORDVPN_CATEGORY=legacy_p2p \
	-e LOCAL_NETWORK=192.168.0.0/16 \
	--restart=always \
	--log-driver json-file \
	--log-opt max-size=10m \
	-p "$seedboxport":"$seedboxport" \
	haugene/transmission-openvpn

# sudo docker container ls
# sudo docker ps

# fetch the container ID
id="$(sudo docker ps --latest --format '{{ .ID }}')"

# output the IP address on the container IP
localip="$(ip-local)"
hostip="$(curl 'http://ipecho.net/plain')"
containerip="$(sudo docker exec -it "$id" curl 'http://ipecho.net/plain')"
function details {
	echo "host ip      =  $hostip"
	echo "seedbox ip   =  $containerip"
	echo "seedbox url  =  http://$localip:$seedboxport"
}
if test "$hostip" != "$containerip"; then
	echo 'seedbox booted successfully'
	details
else
	echo 'seedbox did not connect to the vpn it seems'
	details
	exit 1
fi
