#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

tag="$(github-latest-release 'rfjakob/gocryptfs')"

dir="$HOME/gocryptfs-$tag"
ok rm -Rf "$dir"

git clone --quiet --depth 1 --branch "$tag" 'https://github.com/rfjakob/gocryptfs.git' "$dir" > /dev/null
pushd "$dir" > /dev/null
chmod +x ./build.bash
./build.bash
popd > /dev/null

rm -Rf "$dir"

# gocryptfs --version