#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# check system
if ! is-ubuntu; then
	stderr echo 'only for ubuntu'
	exit 1
fi

# check user config
varfile="$DOROTHY/user/env/share.bash"
if test -f "$varfile"; then
	source "$varfile"
fi
if test -z "${SHARE_GROUP-}"; then
	stderr echo 'USAGE: env SHARE_GROUP=<group> setup-resilio'
	exit 1
fi

# https://help.resilio.com/hc/en-us/articles/206178924
# https://help.resilio.com/hc/en-us/articles/204762449-Guide-to-Linux

# install
if is-apt; then
	echo "deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free" | sudo tee /etc/apt/sources.list.d/resilio-sync.list
	curl -LO http://linux-packages.resilio.com/resilio-sync/key.asc && sudo apt-key add ./key.asc
	sudo apt-get update
	sudo apt-get install resilio-sync
fi

# service
sudo systemctl enable resilio-sync

# permissions
sudo gpasswd -a rslsync "$SHARE_GROUP"
env user=rslsync group=rslsync fix-permissions /etc/resilio-sync/
env user=rslsync group=rslsync fix-permissions /var/lib/resilio-sync/

# configure
sudo vim /lib/systemd/system/resilio-sync.service
sudo vim /etc/resilio-sync/config.json

# start
sudo systemctl daemon-reload
sudo systemctl restart resilio-sync
sudo systemctl status resilio-sync --no-pager

# log
journalctl -u resilio-sync.service --no-pager
