#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# check system
if ! is-ubuntu; then
	stderr echo 'only for ubuntu'
	exit 1
fi

# install
env APT=samba setup-util
env APT=samba-common-bin setup-util

# ensure correct permissions
sudo mkdir -p /etc/samba/credentials/share
sudo chown root:root /etc/samba/credentials
sudo chmod 700 /etc/samba/credentials
sudo chmod 600 /etc/samba/credentials/share

# restart samba
sudo systemctl restart smbd

# verify configuration
testparm
