#!/usr/bin/env bash

function setup_util_bash_versions() (
	source "$DOROTHY/sources/bash.bash"

	# enable DOWNLOAD_BUILD_INSTALL
	source "$(type -P setup-util)"

	# setup
	local version versions options
	versions=(
		# 4.0
		# 4.1
		# 4.2
		# 4.3
		# 4.4
		# 5.0
		5.1
		5.2
	)
	function do_install {
		# dependencies
		setup-util-devel --quiet
		source "$DOROTHY/sources/environment.sh"

		# build
		./configure
		make
	}
	for version in "${versions[@]}"; do
		options=(
			--cli="bash-$version"
			"$@"
			DOWNLOAD="https://ftp.gnu.org/gnu/bash/bash-${version}.tar.gz"
			DOWNLOAD_UNZIP_FORMAT='tar'
			DOWNLOAD_UNZIP_FILTER='bash-*/*'
			DOWNLOAD_BUILD_INSTALL='do_install'
			DOWNLOAD_BUILD_GLOB='*/bash'
		)
		setup_util "${options[@]}"
	done
)

# fire if invoked standalone
if [[ "$0" = "${BASH_SOURCE[0]}" ]]; then
	setup_util_bash_versions "$@"
fi
