#!/usr/bin/env bash
source "$DOROTHY/sources/bash.bash"

function parent() {
	echo "parent before: ${var-}"
	var='parent'
	function child() {
		echo "child before: ${var-}"
		var='child'
		function grandchild() (
			echo "grandchild before: ${var-}"
			var='grandchild'
			echo "grandchild after: ${var-}"
		)
		grandchild
		echo "child after: ${var-}"
	}
	child
	echo "parent after: ${var-}"
}

parent
echo
child
echo
grandchild
echo
echo "${var-}"
