#!/usr/bin/env bash
set -Eeuo pipefail
shopt -s inherit_errexit
# shopt -s lastpipe
# set -bmT

echo 'one'

mapfile -t tuples < <(exit 1)
# ^ what option do I need to enable so the error exit code from this is not ignored

echo 'two'

mapfile -t tuples <<<"$(exit 1)"

echo 'three'

mapfile -t tuples < <(exit 1)
wait $!

echo 'four'

f="$(mktemp)"
exit 1 >"$f"
mapfile -t tuples <"$f"

echo 'five'
