#!/usr/bin/env bash
source "$DOROTHY/sources/bash.bash"

dir="${1:-"$(pwd)"}"

if confirm-positive --ppid=$$ -- "This will zero-length every file inside $dir, are you sure?" "$(ls -la "$dir")"; then
	while IFS= read -r line; do
		printf '' >"$line"
	done < <(ls -1 "$dir")
fi
